=head1 NAME

Cbars - A small and humble tool to observe server loads

=head1 SYNOPSIS

cpuinfo [LIST OF HOSTNAMES] 

=head2 Tested platforms

This version of Cbars has only been tested on Debian GNU/Linux Wheezy.

There is no release made yet atm. So please come back later and don't use this yet.

=head1 LICENSE

See package description or project website.

=head1 AUTHOR

Paul Buetow - <http://cpuinfo.buetow.org>

=cut
